import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { AvatarSection } from "@/components/avatar-section";
import { Skeleton } from "@/components/ui/skeleton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row gap-4 min-h-screen items-start justify-center bg-background">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col justify-between gap-4 w-60 border-r border-border h-screen p-4">
              <div className="flex flex-col gap-4">
                <div className="space-y-2">
                  <h1 className="text-2xl font-bold text-primary">MusicSky</h1>
                  <h2 className="text-sm text-muted-foreground">
                    Listen and share the music in the Atmosphere.
                  </h2>
                </div>
                {Array.from({ length: 5 }).map((_, index) => (
                  <Skeleton key={index} className="w-full h-9 rounded-full" />
                ))}
              </div>
              <div className="flex flex-col gap-4">
                <AvatarSection />
                <Button asChild>
                  <Link href="/upload">Upload a song</Link>
                </Button>
              </div>
            </div>
            <div className="max-w-lg w-full pb-4 px-4 pt-8">{children}</div>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
